name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 4 * * *'  # Runs daily at 04:30 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 22f2000757@ds.study.iitm.ac.in - Modify File
        run: |
          echo "Daily commit on $(date)" >> daily-log.txt

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily commit - $(date)" || echo "Nothing to commit"
          git push
