workflow_code = """
name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 22f2000757@ds.study.iitm.ac.in - Modify File
        run: echo "Commit at $(date)" >> daily-log.txt

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily commit"
          git push
"""

with open(".github/workflows/daily-commit.yml", "w") as f:
    f.write(workflow_code)
