name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 4 * * *'  # Runs every day at 4:30 AM UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 22f2000757@ds.study.iitm.ac.in - Modify File
        run: echo "Commit at $(date)" >> daily-log.txt

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily commit"
          git push
