name: Daily Commit

on:
  schedule:
    - cron: '30 4 * * *'  # Runs every day at 04:30 UTC
  workflow_dispatch:      # Allows manual run from GitHub UI

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add log line (22f2000757@ds.study.iitm.ac.in)
        run: |
          echo "Log entry from $(date -u)" >> daily-log.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily commit"
          git push
